---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
  - package-ecosystem: pip
    directory: "/requirements"
    ignore:
      - dependency-name: "django"
        # Ignore non-LTS Django releases
        # https://www.djangoproject.com/download/#supported-versions
        versions:
          - ">=4.0,<4.2"
          - ">=5.0,<5.2"
    schedule:
      interval: daily
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
