---
name: "Build DEV/TEST docker image"
description: "Build the docker image for dev and test purpose"
inputs:
  docker-hub-username:
    required: true
    description: "The docker hub username"
  docker-hub-token:
    required: true
    description: "The docker hub token"

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker-hub-username }}
        password: ${{ inputs.docker-hub-token }}

    - name: Build the docker image
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 15
        retry_wait_seconds: 20
        max_attempts: 3
        command: |
          docker-compose -f docker-compose-dev.yml build
