---
name: Code Checks (Linting and Testing)

"on":
  pull_request:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "*version.txt"
      - "docs/**"
      - "tools/**"
  schedule:
    - cron: "0 6 * * 5"  # At 07:00 on Friday

jobs:
  # JOB to run change detection via https://github.com/dorny/paths-filter
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.lint }}
      frontend: ${{ steps.filter.outputs.test }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - name: Create filters
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            lint:
              - '**/*.py'
              - '**/*.yml'
              - '**/*.yaml'
            test:
              - 'app/**'
              - 'config/**'
              - 'docker/**'
              - 'requirements/**'
              - 'scripts/**'
              - 'tests/**'
              - 'docker-compose*'
              - 'Makefile'
              - 'manage.py'
              - 'pyproject.toml'
              - 'setup.cfg'

  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_RO }}

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build the docker image
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          retry_wait_seconds: 20
          max_attempts: 3
          command: |
            docker-compose -f docker-compose-dev.yml build

      - name: Create docker image copy
        run: docker save photogrepo > /tmp/photogrepo.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: photogrepo
          path: /tmp/photogrepo.tar

  lint:
    runs-on: ubuntu-latest
    needs: [ changes, docker_build ]
    if: ${{ needs.changes.outputs.lint == 'true' }}
    steps:
      - name: Debug print all changed files
        run: echo "${{ needs.changes.outputs.lint_files }}"

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Load environment vars
        id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          path: .github/workflows/env_vars.txt
          log-variables: true

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: photogrepo
          path: /tmp

      - name: Load docker image copy
        run: docker load --input /tmp/photogrepo.tar

      - name: Run linter
        run: make docker_lint

  test:
    runs-on: ubuntu-latest
    needs: [ changes, docker_build, lint ]
    if: ${{ needs.changes.outputs.test == 'true' }}
    steps:
      - name: Debug print all changed files
        run: echo "${{ needs.changes.outputs.test_files }}"

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Load environment vars
        id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          path: .github/workflows/env_vars.txt
          log-variables: true

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: photogrepo
          path: /tmp

      - name: Load docker image copy
        run: docker load --input /tmp/photogrepo.tar

      - name: Run tests
        run: make docker_test
