---
name: Build docker image

"on":
  workflow_call:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_RO }}

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build the docker image
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          retry_wait_seconds: 20
          max_attempts: 3
          command: |
            docker-compose -f docker-compose-dev.yml build
